// src/client/components/craft/PlayerPicker.tsx
/**
 * Copyright (C) 2026 Luiz Ferraz
 *
 * This file is part of Ordum Dashboard.
 *
 * Ordum Dashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Ordum Dashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Ordum Dashboard. If not, see <https://www.gnu.org/licenses/>.
 */
import { useStore } from "@nanostores/preact";
import { useRef, useState, useEffect, useCallback } from "preact/hooks";
import { jita } from "../../../common/api";
import { $player } from "../../stores/player";

interface PlayerResult {
  entity_id: string;
  username: string;
}

export default function PlayerPicker() {
  const player = useStore($player);
  const [open, setOpen] = useState(false);
  const [highlightIdx, setHighlightIdx] = useState(-1);
  const [results, setResults] = useState<PlayerResult[]>([]);
  const [loading, setLoading] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout>>(null);

  // Debounced API search whenever the player input changes
  useEffect(() => {
    if (debounceRef.current != null) clearTimeout(debounceRef.current);

    const q = player.trim();
    if (q.length < 2) {
      setResults([]);
      return;
    }

    setLoading(true);
    debounceRef.current = setTimeout(async () => {
      try {
        const page = await jita.listPlayers({ q });
        setResults(
          page.players.map((p) => ({
            entity_id: p.entityId,
            username: p.username,
          })),
        );
      } catch {
        setResults([]);
      } finally {
        setLoading(false);
      }
    }, 300);

    return () => {
      if (debounceRef.current != null) clearTimeout(debounceRef.current);
    };
  }, [player]);

  useEffect(() => {
    if (highlightIdx >= 0 && dropdownRef.current) {
      const el = dropdownRef.current.children[highlightIdx] as HTMLElement;
      if (el) el.scrollIntoView({ block: "nearest" });
    }
  }, [highlightIdx]);

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (
        !(e.target instanceof HTMLElement) ||
        !e.target.closest(".player-search-container")
      ) {
        setOpen(false);
      }
    }
    document.addEventListener("click", handleClick);
    return () => document.removeEventListener("click", handleClick);
  }, []);

  const pickPlayer = useCallback((name: string) => {
    $player.set(name);
    setOpen(false);
    setHighlightIdx(-1);
  }, []);

  function handleInput(e: Event) {
    $player.set((e.target as HTMLInputElement).value);
    setOpen(true);
    setHighlightIdx(-1);
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      if (!open) setOpen(true);
      setHighlightIdx((i) => Math.min(i + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setHighlightIdx((i) => Math.max(i - 1, 0));
    } else if (e.key === "Enter") {
      e.preventDefault();
      if (highlightIdx >= 0 && highlightIdx < results.length) {
        pickPlayer(results[highlightIdx]!.username);
      }
    } else if (e.key === "Escape") {
      setOpen(false);
      setHighlightIdx(-1);
    }
  }

  function handleFocus() {
    if (results.length > 0) setOpen(true);
  }

  return (
    <div class="input-group player-search-container">
      <label for="player-search">Player (optional)</label>
      <div class="search-input-wrapper">
        <span class="search-icon">👤</span>
        <input
          type="text"
          class="player-search"
          id="player-search"
          placeholder="Type to search players..."
          autocomplete="off"
          ref={inputRef}
          value={player}
          onInput={handleInput}
          onKeyDown={handleKeydown}
          onFocus={handleFocus}
        />
        {player && (
          <button
            type="button"
            class="clear-btn"
            onClick={() => {
              $player.set("");
              setOpen(false);
            }}
          >
            ✕
          </button>
        )}
      </div>
      {open && (results.length > 0 || loading) && (
        <div class="search-dropdown" ref={dropdownRef}>
          {loading && results.length === 0 && (
            <div class="dropdown-loading">Searching…</div>
          )}
          {results.map((m, i) => (
            <button
              type="button"
              class={`search-option ${i === highlightIdx ? "highlighted" : ""}`}
              onClick={() => pickPlayer(m.username)}
              onMouseEnter={() => setHighlightIdx(i)}
              role="option"
              aria-selected={i === highlightIdx}
              key={m.entity_id}
            >
              <span>{m.username}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// src/components/craft/PlayerPicker.svelte
<script lang="ts">
  import { tick } from 'svelte';
  import { $player as player } from '../../lib/craft-store';

  interface Props {
    members: { entity_id: number; user_name: string }[];
  }

  let { members }: Props = $props();

  let open = $state(false);
  let highlightIdx = $state(-1);
  let inputEl: HTMLInputElement | undefined = $state();
  let dropdownEl: HTMLDivElement | undefined = $state();

  let filtered = $derived.by(() => {
    const q = $player.toLowerCase().trim();
    if (q.length === 0) return members;
    return members.filter(m => m.user_name.toLowerCase().includes(q));
  });

  $effect(() => {
    if (highlightIdx >= 0 && dropdownEl) {
      const el = dropdownEl.children[highlightIdx] as HTMLElement;
      if (el) el.scrollIntoView({ block: 'nearest' });
    }
  });

  function pickPlayer(name: string) {
    player.set(name);
    open = false;
    highlightIdx = -1;
  }

  function handleInput(e: Event) {
    $player = (e.target as HTMLInputElement).value;
    open = true;
    highlightIdx = -1;
    // If cleared, reset player
    if (!$player.trim()) {
      $player.set('');
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (!open) open = true;
      highlightIdx = Math.min(highlightIdx + 1, filtered.length - 1);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      highlightIdx = Math.max(highlightIdx - 1, 0);
    } else if (e.key === 'Enter') {
      e.preventDefault();
      if (highlightIdx >= 0 && highlightIdx < filtered.length) {
        pickPlayer(filtered[highlightIdx].user_name);
      }
    } else if (e.key === 'Escape') {
      open = false;
      highlightIdx = -1;
    }
  }

  function handleFocus() {
    if (filtered.length > 0) open = true;
  }

  function handleDocumentClick(e: MouseEvent) {
    if (!(e.target instanceof HTMLElement) || !e.target.closest('.player-search-container')) {
      open = false;
    }
  }
</script>

<svelte:document onclick={handleDocumentClick} />

<div class="input-group player-search-container">
  <label for="player-search">Player (optional)</label>
  <div class="search-input-wrapper">
    <span class="search-icon">👤</span>
    <input
      type="text"
      class="player-search"
      id="player-search"
      placeholder="Type to search players..."
      autocomplete="off"
      bind:this={inputEl}
      value={$player}
      oninput={handleInput}
      onkeydown={handleKeydown}
      onfocus={handleFocus}
    />
    {#if $player}
      <button type="button" class="clear-btn" onclick={() => { $player = ''; open = false; }}>✕</button>
    {/if}
  </div>
  {#if open && filtered.length > 0}
    <div class="search-dropdown" bind:this={dropdownEl}>
      {#each filtered as m, i}
        <button
          type="button"
          class="search-option"
          class:highlighted={i === highlightIdx}
          onclick={() => pickPlayer(m.user_name)}
          onmouseenter={() => highlightIdx = i}
          role="option"
          aria-selected={i === highlightIdx}
        >
          <span>{m.user_name}</span>
        </button>
      {/each}
    </div>
  {/if}
</div>

<style>
  .input-group {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .input-group label {
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-muted);
    font-weight: 600;
  }
  .player-search-container { position: relative; min-width: 200px; }
  .search-input-wrapper {
    position: relative;
    display: flex;
    align-items: center;
  }
  .search-icon {
    position: absolute;
    left: 10px;
    font-size: 0.9rem;
    pointer-events: none;
  }
  .player-search {
    width: 100%;
    padding-left: 32px;
    padding-right: 28px;
    background: var(--bg-surface-2);
    border: 1px solid var(--border);
    border-radius: 8px;
    color: var(--text);
    font-size: 0.85rem;
    outline: none;
    transition: all 0.2s ease;
    height: 34px;
  }
  .player-search:focus {
    border-color: var(--accent);
    box-shadow: 0 0 0 3px var(--accent-glow);
  }
  .clear-btn {
    position: absolute;
    right: 6px;
    background: none;
    border: none;
    color: var(--text-muted);
    cursor: pointer;
    font-size: 0.8rem;
    padding: 2px 4px;
  }
  .clear-btn:hover { color: var(--red); }
  .search-dropdown {
    position: absolute;
    top: calc(100% + 4px);
    left: 0;
    right: 0;
    z-index: 100;
    background: var(--bg-surface-2);
    border: 1px solid var(--border);
    border-radius: 8px;
    max-height: 200px;
    overflow-y: auto;
    box-shadow: 0 12px 32px rgba(0,0,0,0.4);
    padding: 4px;
  }
  .search-option {
    width: 100%;
    text-align: left;
    padding: 8px 12px;
    cursor: pointer;
    font-size: 0.85rem;
    display: flex;
    align-items: center;
    gap: 10px;
    border-radius: 6px;
    transition: background 0.15s;
    background: none;
    border: none;
    color: var(--text);
  }
  .search-option:hover, .search-option.highlighted {
    background: var(--bg-surface-3);
  }
</style>
