// src/components/CraftPlanner.tsx
import type { IndexItem } from '../lib/craft-store';
import CraftConfiguration from './craft/CraftConfiguration';
import CraftingPlan from './craft/CraftingPlan';

interface Props {
  itemIndex: IndexItem[];
  members: { entity_id: number; user_name: string }[];
}

export default function CraftPlanner({ itemIndex, members = [] }: Props) {
  return (
    <>
      <CraftConfiguration itemIndex={itemIndex} members={members} />
      <CraftingPlan />
    </>
  );
}

// src/components/CraftPlanner.svelte
<script lang="ts">
  import type { IndexItem } from '../lib/craft-store';
  import CraftConfiguration from './craft/CraftConfiguration.svelte';
  import CraftingPlan from './craft/CraftingPlan.svelte';

  interface Props {
    itemIndex: IndexItem[];
    members: { entity_id: number; user_name: string }[];
  }

  let { itemIndex, members = [] }: Props = $props();
</script>

<CraftConfiguration {itemIndex} {members} />
<CraftingPlan />
